module.exports = {
  plugins: [
    'qunit',
  ],
  rules: {
    'qunit/assert-args': 'error',
    'qunit/literal-compare-order': 'error',
    'qunit/no-arrow-tests': 'error',
    'qunit/no-assert-equal': 'off',
    'qunit/no-assert-logical-expression': 'off',
    'qunit/no-async-in-loops': 'error',
    'qunit/no-async-test': 'error',
    'qunit/no-commented-tests': 'error',
    'qunit/no-compare-relation-boolean': 'error',
    'qunit/no-conditional-assertions': 'error',
    'qunit/no-early-return': 'error',
    'qunit/no-global-assertions': 'off',
    'qunit/no-global-expect': 'off',
    'qunit/no-global-module-test': 'off',
    'qunit/no-global-stop-start': 'off',
    'qunit/no-init': 'error',
    'qunit/no-jsdump': 'error',
    'qunit/no-negated-ok': 'error',
    'qunit/no-ok-equality': 'error',
    'qunit/no-only': 'error',
    'qunit/no-qunit-push': 'error',
    'qunit/no-qunit-start-in-tests': 'error',
    'qunit/no-qunit-stop': 'error',
    'qunit/no-reassign-log-callbacks': 'error',
    'qunit/no-reset': 'error',
    'qunit/no-setup-teardown': 'error',
    'qunit/no-test-expect-argument': 'error',
    'qunit/no-throws-string': 'error',
    'qunit/require-expect': 'off',
    'qunit/resolve-async': 'off',
  },
};
